
interface I18nTranslation {
    home: string
    more_details: string
    section_1_title: string
    section_2_title: string
    section_2_subtitle: string
    section_3_title: string
    section_3_subtitle: string
    section_3_content: string
    section_4_title: string
    section_4_port_1: string
    section_4_port_2: string
    section_4_port_3: string
    section_4_port_4: string
    section_4_port_5: string
    section_4_port_6: string
    section_4_port_7: string
    section_5_case_1: string
    section_5_case_2: string
    section_5_case_3: string
    section_5_case_4: string
    section_5_case_5: string
    section_5_case_6: string
    section_5_case_7: string
    section_5_case_8: string
    section_5_case_9: string
    section_6_title: string
    section_6_container_1_title: string
    section_6_container_1_item_1: string
    section_6_container_1_item_2: string
    section_6_container_1_item_3: string
    section_6_container_1_item_4: string
    section_6_container_1_item_5: string
    section_6_container_1_item_6: string
    section_6_container_1_item_7: string
    section_6_container_1_item_8: string
    section_6_container_2_title: string
    section_6_container_2_item_1: string
    section_6_container_2_item_2: string
    section_6_container_2_item_3: string
    section_7_service_1_title: string
    section_7_service_1_desc: string
    section_7_service_1_img_1: string
    section_7_service_1_img_2: string
    section_7_service_1_img_3: string
    section_7_service_1_img_4: string
    section_7_service_1_img_5: string
    section_7_service_2_title: string
    section_7_service_2_desc: string
    section_7_service_2_img_1: string
    section_7_service_2_img_2: string
    section_7_service_2_img_3: string
    section_7_service_2_img_4: string
    section_7_service_3_title: string
    section_7_service_3_desc: string
    section_7_service_3_img_1: string
    section_7_service_3_img_2: string
    section_7_service_3_img_3: string
    section_7_service_3_img_4: string
    section_7_service_4_title: string
    section_7_service_4_desc: string
    section_7_service_4_img_1: string
    section_7_service_4_img_2: string
    section_7_service_4_img_3: string
    section_7_service_4_img_4: string
    section_7_service_5_title: string
    section_7_service_5_desc: string
    section_7_service_5_img_1: string
    section_7_service_5_img_2: string
    section_7_service_5_img_3: string
    section_7_service_5_img_4: string
    section_7_service_6_title: string
    section_7_service_6_desc: string
    section_7_service_6_img_1: string
    section_7_service_6_img_2: string
    section_7_service_6_img_3: string
    section_7_service_6_img_4: string
    section_7_service_7_title: string
    section_7_service_7_desc: string
    section_7_service_7_img_1: string
    section_7_service_7_img_2: string
    section_7_service_7_img_3: string
    section_7_service_7_img_4: string
    section_7_service_8_title: string
    section_7_service_8_desc: string
    section_7_service_8_img_1: string
    section_7_service_8_img_2: string
    section_7_service_8_img_3: string
    section_7_service_8_img_4: string
    section_7_service_9_title: string
    section_7_service_9_desc: string
    section_7_service_9_img_1: string
    section_7_service_9_img_2: string
    section_7_service_9_img_3: string
    section_7_service_9_img_4: string
    section_7_service_9_img_5: string
    section_7_service_9_img_6: string
    section_7_service_9_img_7: string
    section_7_service_9_img_8: string
    footer_col_1_title: string
    footer_col_1_nav_1: string
    footer_col_1_nav_2: string
    footer_col_1_nav_3: string
    footer_col_2_title: string
    footer_col_2_nav_1: string
    footer_col_2_nav_2: string
    footer_col_2_nav_3: string
    footer_col_2_nav_4: string
    footer_col_2_nav_5: string
    footer_col_2_nav_6: string
    footer_col_2_nav_7: string
    footer_col_2_nav_8: string
    footer_col_2_nav_9: string
    footer_col_2_nav_10: string
    footer_col_2_nav_11: string
    footer_col_3_title: string
    footer_col_3_content_1: string
    footer_col_3_content_2: string
    footer_col_3_content_3: string
    footer_col_3_content_4: string
    footer_copyright: string

    about_us_title: string
    about_us_subtitle: string
    about_us_content: string
    about_us_img_1: string
    about_us_img_2: string
    about_us_img_3: string
    about_us_img_4: string
    back_page: string

    service_1_title: string
    service_1_subtitle: string
    service_1_content: string
    service_1_img_1: string
    service_1_img_2: string
    service_1_img_3: string
    service_1_img_4: string
    service_1_img_5: string
    service_2_title: string
    service_2_subtitle: string
    service_2_content: string
    service_2_img_1: string
    service_2_img_2: string
    service_2_img_3: string
    service_2_img_4: string
    service_3_title: string
    service_3_subtitle: string
    service_3_content: string
    service_3_img_1: string
    service_3_img_2: string
    service_3_img_3: string
    service_3_img_4: string
    service_4_title: string
    service_4_subtitle: string
    service_4_content: string
    service_4_img_1: string
    service_4_img_2: string
    service_4_img_3: string
    service_4_img_4: string
    service_5_title: string
    service_5_subtitle: string
    service_5_content: string
    service_5_img_1: string
    service_5_img_2: string
    service_5_img_3: string
    service_5_img_4: string
    service_6_title: string
    service_6_subtitle: string
    service_6_content: string
    service_6_img_1: string
    service_6_img_2: string
    service_6_img_3: string
    service_6_img_4: string
    service_7_title: string
    service_7_subtitle: string
    service_7_content: string
    service_7_img_1: string
    service_7_img_2: string
    service_7_img_3: string
    service_7_img_4: string
    service_8_title: string
    service_8_subtitle: string
    service_8_content: string
    service_8_img_1: string
    service_8_img_2: string
    service_8_img_3: string
    service_8_img_4: string
    service_9_title: string
    service_9_subtitle: string
    service_9_content: string
    service_9_img_1: string
    service_9_img_2: string
    service_9_img_3: string
    service_9_img_4: string
    service_9_img_5: string
    service_9_img_6: string
    service_9_img_7: string
    service_9_img_8: string
}

interface I18nRoot {
    translation: I18nTranslation
}

interface FilesAPIResponse {
    'service-block-2': string
    about_us_img_1: string
    about_us_img_2: string
    about_us_img_3: string
    about_us_img_4: string
    'about-us-banner': string
    'about-us-photo': string
    'port-anping': string
    'port-kaoshiung': string
    'port-keelung': string
    'port-sauo': string
    'port-taichung': string
    'port-taipei': string
    section_5_case_1: string
    section_5_case_2: string
    section_5_case_3: string
    section_5_case_4: string
    section_5_case_5: string
    section_5_case_6: string
    section_5_case_7: string
    section_5_case_8: string
    section_7_service_1_img_1: string
    section_7_service_1_img_2: string
    section_7_service_1_img_3: string
    section_7_service_1_img_4: string
    section_7_service_1_img_5: string
    section_7_service_2_img_1: string
    section_7_service_2_img_2: string
    section_7_service_2_img_3: string
    section_7_service_3_img_1: string
    section_7_service_3_img_2: string
    section_7_service_3_img_3: string
    section_7_service_4_img_1: string
    section_7_service_4_img_2: string
    section_7_service_4_img_3: string
    section_7_service_5_img_1: string
    section_7_service_5_img_2: string
    section_7_service_5_img_3: string
    section_7_service_6_img_1: string
    section_7_service_6_img_2: string
    section_7_service_6_img_3: string
    section_7_service_7_img_1: string
    section_7_service_7_img_2: string
    section_7_service_7_img_3: string
    section_7_service_7_img_4: string
    section_7_service_8_img_1: string
    section_7_service_8_img_2: string
    section_7_service_8_img_3: string
    section_7_service_9_img_1: string
    section_7_service_9_img_2: string
    section_7_service_9_img_3: string
    section_7_service_9_img_4: string
    section_7_service_9_img_5: string
    section_7_service_9_img_6: string
    section_7_service_9_img_7: string
    service_5_img_1: string
    service_5_img_2: string
    service_5_img_3: string
    service_8_img_3: string
    'service-banner': string
    'service-block-1': string
}